## Lista 7 ##

### Zadanie 1. - podstawy sortowania ###

Zaimplementuj algorytm sortowania wektora liczb całkowitych względem kolejnych cyfr (od najbardziej znaczącej) tak, aby kolejne cyfry sortować raz malejąco, raz rosnąco (naprzemiennie). Dokładniej, posortuj tak, aby kolejne liczby o takim samej pierwszej cyfrze zostały dodatkowo posortowane względem drugiej cyfry, a liczby o takich samych: pierwszej i drugiej cyfrze zostały posortowane względem trzeciej cyfry, itd.

Zadanie wykonaj wielokrotnie korzystając z jednego (wybranego przez siebie) stabilnego algorytmu sortowania.

In [2]:
import numpy as np

In [3]:
VECTOR = list(np.random.randint(100, 1000, 100))
print(VECTOR)

[878, 807, 289, 358, 233, 996, 431, 506, 943, 724, 936, 404, 679, 690, 900, 812, 201, 432, 995, 876, 723, 707, 710, 614, 377, 578, 428, 803, 839, 660, 224, 292, 432, 293, 166, 148, 929, 536, 410, 409, 899, 965, 161, 802, 586, 938, 631, 476, 235, 817, 700, 782, 442, 982, 506, 241, 879, 973, 132, 254, 932, 335, 156, 495, 971, 350, 803, 234, 497, 225, 256, 179, 965, 573, 409, 493, 286, 427, 506, 491, 505, 836, 489, 162, 399, 331, 941, 671, 822, 210, 256, 727, 722, 454, 945, 304, 484, 836, 646, 484]


Wybrany algorytm sortujący - sortowanie szybkie - zaimplemntowany dwukrotnie dla sortowania rosnącego i sortowania malejącego.

In [4]:
def quick_sort_asc(arr, low, high):
        if low > high or low < 0:
            return
        
        p, arr =  partition_asc(arr, low, high)

        quick_sort_asc(arr, low, p - 1)
        quick_sort_asc(arr, p + 1, high)

        return arr


def partition_asc(arr, low, high):
    piv = arr[high]

    i = low - 1

    for j in range(low, high):
        if arr[j] <= piv:
            i += 1
            arr[j], arr[i] = arr[i], arr[j]
    
    i += 1
    arr[i], arr[high] = arr[high], arr[i]
    
    return i, arr

def quick_sort_desc(arr, low, high):
    if low > high: # or high >= len(arr):
        return
    
    p, arr =  partition(arr, low, high)

    quick_sort_desc(arr, low, p - 1)
    quick_sort_desc(arr, p + 1, high)

    return arr


def partition(arr, low, high):
    piv = arr[high]

    i = low - 1

    for j in range(low, high):
        if arr[j] >= piv:
            i += 1
            arr[j], arr[i] = arr[i], arr[j]
    
    i += 1
    arr[i], arr[high] = arr[high], arr[i]
    
    return i, arr

Sortowanie listy wedłu podanych w treści zadania zasad.

In [6]:
def sort_vector(vec):
    l = len(str(max(vec))) # sprawdzenie ile cyfr ma ajwiększa liczba z listy
    prefixes = list()
    # stworzenie listy prefixów
    for n in range(l, 1, -1):
        prefixes.append([i * 10 ** (n-1) for i in range(10 ** (l - n + 1)  + 1)])

    rev = 1
    vec = quick_sort_asc(vec, 0, len(vec) - 1)

    for pref in prefixes:

        for p in range(len(pref) - 1):

            temp = [v for v in vec if (v >= pref[p] and v < pref[p+1])]
            if len(temp):
                low = vec.index(temp[0])
                high = vec.index(temp[-1])
                if rev:
                    temp = quick_sort_desc(temp, 0, len(temp) - 1)                    
                else:
                    temp = quick_sort_asc(temp, 0, len(temp) - 1)


                #temp = sorted(temp, reverse=rev)
                vec[low:high + 1] = temp

        if rev:
            rev = 0
        else:
            rev = 1
    return vec
        


V_NEW = sort_vector(VECTOR)
print('\nPOSORTOWANA LISTA:')
print(V_NEW)


POSORTOWANA LISTA:
[179, 161, 162, 166, 156, 148, 132, 292, 293, 286, 289, 254, 256, 256, 241, 233, 234, 235, 224, 225, 210, 201, 399, 377, 350, 358, 331, 335, 304, 491, 493, 495, 497, 484, 484, 484, 489, 484, 484, 476, 454, 442, 431, 432, 432, 427, 428, 410, 404, 409, 409, 586, 573, 578, 536, 505, 506, 506, 506, 690, 671, 679, 660, 646, 631, 614, 782, 722, 723, 724, 727, 710, 700, 707, 899, 876, 878, 879, 836, 836, 836, 839, 836, 836, 822, 812, 817, 802, 803, 803, 807, 995, 996, 982, 971, 973, 965, 965, 965, 965, 965, 941, 943, 945, 932, 936, 938, 929, 900]


### Zadanie 2 - ograniczony zbiór wartości ###

Dany jest wektor robotów (z poprzedniej listy). Wykorzystaj algorytm sortowania przez zliczanie do sortowania względem rozdzielczości kamery.

In [ ]:
import numpy as np

In [ ]:
A = np.random.randint(0, 10, 20)
print(A)

In [13]:
def counting_sort(l):
    j = [0] * (max(l) + 1)
    output = [0] * (len(l) + 1)

    for i in l:
        j[i] += 1
    
    for i in range(1, len(j)):
        j[i] += j[i - 1]
    
    for i in range(len(l)):
        a = l[i]
        b = j[a]
        output[b] = a
        j[a] -= 1

    return output

In [14]:
from L6_0_data_structure import create_m_bots

# wektor robotów
robots = create_m_bots(20)
robots = [b.save_robot() for b in robots]
robots

[{'id': '1101', 'typ': 'GUA', 'masa': 539, 'roz': 10},
 {'id': '1010', 'typ': 'WUC', 'masa': 1398, 'roz': 16},
 {'id': '1111', 'typ': 'GNW', 'masa': 151, 'roz': 29},
 {'id': '1110', 'typ': 'NNV', 'masa': 572, 'roz': 15},
 {'id': '0110', 'typ': 'GVW', 'masa': 81, 'roz': 27},
 {'id': '1101', 'typ': 'WNV', 'masa': 282, 'roz': 7},
 {'id': '0011', 'typ': 'GGV', 'masa': 827, 'roz': 6},
 {'id': '0001', 'typ': 'NUG', 'masa': 732, 'roz': 8},
 {'id': '1011', 'typ': 'GVG', 'masa': 1612, 'roz': 24},
 {'id': '1111', 'typ': 'UAA', 'masa': 1965, 'roz': 26},
 {'id': '0001', 'typ': 'VVN', 'masa': 1334, 'roz': 14},
 {'id': '0010', 'typ': 'AAG', 'masa': 1960, 'roz': 8},
 {'id': '0001', 'typ': 'NGV', 'masa': 1503, 'roz': 27},
 {'id': '0110', 'typ': 'WUN', 'masa': 1485, 'roz': 11},
 {'id': '0001', 'typ': 'NNV', 'masa': 62, 'roz': 23},
 {'id': '1000', 'typ': 'AUV', 'masa': 1815, 'roz': 19},
 {'id': '0100', 'typ': 'GWC', 'masa': 1733, 'roz': 11},
 {'id': '1111', 'typ': 'GAG', 'masa': 801, 'roz': 1},
 {'id': 

In [15]:
# wyodrębnienie rozdzielczości u umieszczenie warotści w liście 
L = [i['roz'] for i in robots]
# wywołanie sortowania przez zlicznie
resolutions = counting_sort(L)  
new_robots = []

# idąc po posortowanych rozdzielczościach ponowne scalenie listy robotów
for r in resolutions:
    for bot in robots:
        if bot['roz'] == r:
            new_robots.append(bot)
            robots.remove(bot)

for b in new_robots:
    print(b)

{'id': '1111', 'typ': 'GAG', 'masa': 801, 'roz': 1}
{'id': '1100', 'typ': 'CVA', 'masa': 1172, 'roz': 4}
{'id': '0011', 'typ': 'GGV', 'masa': 827, 'roz': 6}
{'id': '1101', 'typ': 'WNV', 'masa': 282, 'roz': 7}
{'id': '0001', 'typ': 'NUG', 'masa': 732, 'roz': 8}
{'id': '0010', 'typ': 'AAG', 'masa': 1960, 'roz': 8}
{'id': '1101', 'typ': 'GUA', 'masa': 539, 'roz': 10}
{'id': '0110', 'typ': 'WUN', 'masa': 1485, 'roz': 11}
{'id': '0100', 'typ': 'GWC', 'masa': 1733, 'roz': 11}
{'id': '1100', 'typ': 'CWA', 'masa': 1441, 'roz': 13}
{'id': '0001', 'typ': 'VVN', 'masa': 1334, 'roz': 14}
{'id': '1110', 'typ': 'NNV', 'masa': 572, 'roz': 15}
{'id': '1010', 'typ': 'WUC', 'masa': 1398, 'roz': 16}
{'id': '1000', 'typ': 'AUV', 'masa': 1815, 'roz': 19}
{'id': '0001', 'typ': 'NNV', 'masa': 62, 'roz': 23}
{'id': '1011', 'typ': 'GVG', 'masa': 1612, 'roz': 24}
{'id': '1111', 'typ': 'UAA', 'masa': 1965, 'roz': 26}
{'id': '0110', 'typ': 'GVW', 'masa': 81, 'roz': 27}
{'id': '0001', 'typ': 'NGV', 'masa': 1503, '

### Zadanie 3 - sortowanie ciągów ###

Sortowanie pozycyjne (radix sort) \
złożoność : O(n * m)

<b> Pseudokod </b>\
RadixSort(tab[],d)\
wykonuj\
   &nbsp;&nbsp; dla i:=d schodź do 1 wykonuj\
      &nbsp;&nbsp; &nbsp;&nbsp; posortuj stabilnie ciągi według i-tej pozycji;\
end;

In [30]:
L = np.random.randint(0, 7, (20, 3))
L

array([[5, 0, 4],
       [6, 1, 2],
       [5, 2, 3],
       [1, 5, 4],
       [5, 3, 6],
       [0, 1, 4],
       [2, 6, 1],
       [0, 0, 2],
       [5, 1, 6],
       [1, 5, 4],
       [3, 5, 1],
       [1, 0, 3],
       [0, 0, 2],
       [6, 6, 1],
       [6, 3, 5],
       [0, 1, 3],
       [1, 5, 1],
       [6, 2, 6],
       [1, 2, 6],
       [0, 5, 4]])

In [31]:
def radix_sort(t):
    n = len(t[0])
    for i in range(n - 1, -1, -1):
        t = sorted(t, key=lambda x: x[i])
    return t

radix_sort(L)
    

[array([0, 0, 2]),
 array([0, 0, 2]),
 array([0, 1, 3]),
 array([0, 1, 4]),
 array([0, 5, 4]),
 array([1, 0, 3]),
 array([1, 2, 6]),
 array([1, 5, 1]),
 array([1, 5, 4]),
 array([1, 5, 4]),
 array([2, 6, 1]),
 array([3, 5, 1]),
 array([5, 0, 4]),
 array([5, 1, 6]),
 array([5, 2, 3]),
 array([5, 3, 6]),
 array([6, 1, 2]),
 array([6, 2, 6]),
 array([6, 3, 5]),
 array([6, 6, 1])]

### Zadanie 4 - dziel i zwyciężaj ###

- Zaimplementuj algorytm szybkiego sortowania (quicksort) wektora robotów (z poprzedniej listy) względem zadanego parametru.

In [153]:
def quick_sort(arr, low, high):
        if low >= high or low < 0:
            return
        
        p, arr =  partition(arr, low, high)

        quick_sort(arr, low, p - 1)
        quick_sort(arr, p + 1, high)

        return arr


def partition(arr, low, high):
    piv = arr[high]

    i = low - 1

    for j in range(low, high):
        if arr[j] <= piv:
            i += 1
            arr[j], arr[i] = arr[i], arr[j]

    i += 1
    arr[i], arr[high] = arr[high], arr[i]

    return i, arr

def quick_sort_desc(arr, low, high):
    if low >= high or high >= len(arr):
        return

    p, arr =  partition_desc(arr, low, high)

    quick_sort_desc(arr, low, p - 1)
    quick_sort_desc(arr, p + 1, high)

    return arr


def partition_desc(arr, low, high):
    piv = arr[high]

    i = low - 1

    for j in range(low, high):
        if arr[j] >= piv:
            i += 1
            arr[j], arr[i] = arr[i], arr[j]

    i += 1
    arr[i], arr[high] = arr[high], arr[i]

    return i, arr

In [155]:
lis = np.random.randint(0, 10, 10)
print(quick_sort(lis, 0, len(lis)-1))


[0 0 0 3 3 4 6 6 8 9]


In [156]:
def sort_robots(bots, feat, kind=0):
        """
        :param list bots: wektor robotów
        :param feat: cecha według której sortujemy
        :param int kind: 0 -> rosnąco, 1 ->malejąco, 2 -> alfabetycznie
        :return list new_robots: lista robotów posortowana względem zadanego parametru
        """
        # wyciągniecie odpowiedniej cechy
        l = [b[feat] for b in bots]


        if kind == 0:
            l = quick_sort(l, 0, len(l) - 1)
        elif kind == 1:
            l = quick_sort_desc(l, 0, len(l) - 1)
        elif kind == 2:
            l = [str(n) for n in l]
            l = quick_sort(l, 0, len(l) - 1)
        
        
        new_robots = list()
        
        for r in l:
            for bot in bots:
                if bot[feat] == r:
                    new_robots.append(bot)
                    bots.remove(bot)

        return new_robots     


# Wywoałanie funkcji dla pierwszej części zadania
vector = create_m_bots(20)
vector = [b.save_robot() for b in vector]
feauture  = 'roz'
robots = sort_robots(vector, feat=feauture)
print(f"Wektor robotów posortowany względem parametru: {feauture}")
for r in robots:
    print(r)


Wektor robotów posortowany względem parametru: roz
{'id': '1110', 'typ': 'NUW', 'masa': 646, 'roz': 1}
{'id': '1011', 'typ': 'WNN', 'masa': 878, 'roz': 2}
{'id': '1111', 'typ': 'GUG', 'masa': 1196, 'roz': 10}
{'id': '0110', 'typ': 'AUA', 'masa': 673, 'roz': 10}
{'id': '0111', 'typ': 'WAC', 'masa': 1821, 'roz': 15}
{'id': '0000', 'typ': 'VGV', 'masa': 802, 'roz': 20}
{'id': '0100', 'typ': 'GGA', 'masa': 1072, 'roz': 20}
{'id': '0000', 'typ': 'NWC', 'masa': 1002, 'roz': 21}
{'id': '0111', 'typ': 'WGG', 'masa': 1464, 'roz': 22}
{'id': '1111', 'typ': 'CUN', 'masa': 71, 'roz': 23}
{'id': '1000', 'typ': 'GWC', 'masa': 1126, 'roz': 23}
{'id': '1110', 'typ': 'NVW', 'masa': 909, 'roz': 23}
{'id': '0001', 'typ': 'AUV', 'masa': 659, 'roz': 24}
{'id': '1110', 'typ': 'NCW', 'masa': 1988, 'roz': 25}
{'id': '1010', 'typ': 'NWG', 'masa': 1603, 'roz': 26}
{'id': '0001', 'typ': 'CGA', 'masa': 1935, 'roz': 27}
{'id': '1011', 'typ': 'NCG', 'masa': 1044, 'roz': 28}
{'id': '1001', 'typ': 'NUU', 'masa': 1111

- Rozwiń napisaną procedurę tak, aby przyjmowała listę parametrów robota (w zadanej kolejności, niekoniecznie wszystkie) wraz z kierunkiem sortowania (nierosnąco, niemalejąco, alfabetycznie, itd.). Sortowanie wykonaj po wszystkich zadanych parametrach (w zadanej kolejności i zadanym kierunku sortowania) tak, aby kolejne elementy listy o takim samym pierwszym parametrze zostały posortowanewzględem drugiego parametru, a o takim samym pierwszym i drugim parametrze – względem trzeciego parametru itd. Uwaga: Zwróć uwagę na stabilność procedury sortowania.

Do rozwiązania tego podpunktu wykorzystamy powyższą funkcję quicksort oraz sposób myślenia radix sort z zadania 3.

In [157]:
vector = create_m_bots(100)
vector = [b.save_robot() for b in vector]

In [159]:
features = {
        'id': 0,
        'roz': 1,
        'masa': 1,
        'typ': 2,
    }
feat_list = list(features.keys())
# odwrócenie listy cech
feat_list.reverse()
feat_list

['typ', 'masa', 'roz', 'id']

In [160]:
for f in feat_list:
    vector = sort_robots(bots=vector, feat=f, kind=features[f])
    
vector

[{'id': '0000', 'typ': 'NUV', 'masa': 811, 'roz': 25},
 {'id': '0000', 'typ': 'WUW', 'masa': 1036, 'roz': 15},
 {'id': '0000', 'typ': 'ANN', 'masa': 1098, 'roz': 13},
 {'id': '0000', 'typ': 'GCU', 'masa': 52, 'roz': 4},
 {'id': '0001', 'typ': 'NNV', 'masa': 296, 'roz': 28},
 {'id': '0001', 'typ': 'AGN', 'masa': 1312, 'roz': 26},
 {'id': '0001', 'typ': 'ACV', 'masa': 1298, 'roz': 20},
 {'id': '0001', 'typ': 'GGV', 'masa': 927, 'roz': 18},
 {'id': '0001', 'typ': 'WNV', 'masa': 765, 'roz': 15},
 {'id': '0001', 'typ': 'VGC', 'masa': 173, 'roz': 14},
 {'id': '0001', 'typ': 'NAV', 'masa': 1013, 'roz': 20},
 {'id': '0001', 'typ': 'NNN', 'masa': 428, 'roz': 15},
 {'id': '0010', 'typ': 'CUV', 'masa': 1526, 'roz': 22},
 {'id': '0010', 'typ': 'GVC', 'masa': 181, 'roz': 22},
 {'id': '0010', 'typ': 'ANW', 'masa': 1233, 'roz': 21},
 {'id': '0010', 'typ': 'NUU', 'masa': 451, 'roz': 20},
 {'id': '0010', 'typ': 'CUG', 'masa': 1787, 'roz': 16},
 {'id': '0010', 'typ': 'WCN', 'masa': 678, 'roz': 8},
 {'id

### Zadanie 5 - wizualizacja sortowania ###

- Zaimplementuj algorytm sortowania przez kopcowanie.

 - Proces sortowania przedstaw graficznie (np. korzystając z wykresu kolumnowego matplotlib). Wizualizacja ma wyświetlać kolejne kroki algorytmu, gdzie kolejny krok zachodzi po wykonaniu elementarnej operacji (porównywania liczb, zmiany położenia liczb w ciągu, itd.).
 - Wykonaj analogiczną wizualizację dla algorytmu sortowania szybkiego (quicksort). Obie wizualizacje przedstaw (wyświetl) równolegle.

In [89]:
import matplotlib.pyplot as plt
import multiprocessing as mp
import numpy as np


size = 20
INTERVAL = 0.5
L = np.random.randint(0, 100, size)
X = np.arange(size)

def heap_sort_global(l):
    def heapify(arr, n, i):
        largest = i # Ustawienie największego jako ojciec
        l = 2 * i + 1	 # lewy syn = 2*i + 1
        r = 2 * i + 2	 # prawy syn = 2*i + 2

        # Sprwdzamy czy lewy syn istnieje
        # i jest większy od ojca
        if l < n and arr[largest] < arr[l]:
            largest = l

        # Sprwdzamy czy prawy syn istnieje
        # i jest większy od ojca
        if r < n and arr[largest] < arr[r]:
            largest = r

        # Zmiana ojca jeśli spełniony jest warunek
        if largest != i:
            
            arr[i], arr[largest] = arr[largest], arr[i] # swap

            plt.bar(X, arr)
            plt.title('Sortowanie przez kopcowanie')
            plt.pause(INTERVAL)
            plt.clf()


            # ponowne wywołanie kopcowania
            heapify(arr, n, largest)


    def heapSort(arr):
        n = len(arr)

        # Budowanie największego kopca
        for i in range(n//2 - 1, -1, -1):
            heapify(arr, n, i)

        # ektrakcja elementów
        for i in range(n-1, 0, -1):

            arr[i], arr[0] = arr[0], arr[i] # zamiana

            plt.bar(X, arr)
            plt.title('Sortowanie przez kopcowanie')
            plt.pause(INTERVAL)
            plt.clf()

            heapify(arr, i, 0)

    heapSort(l)



def quic_sort_global(l):
    def quick_sort(arr, low, high):
        if low > high: # or high >= len(arr):
            return
        
        p, arr =  partition(arr, low, high)

        quick_sort(arr, low, p - 1)
        quick_sort(arr, p + 1, high)

        return arr


    def partition(arr, low, high):
        piv = arr[high]

        i = low - 1

        for j in range(low, high):
            if arr[j] <= piv:
                i += 1
                arr[j], arr[i] = arr[i], arr[j]

                plt.bar(X, arr)
                plt.title('Quicksort - sortowanie szybkie')
                plt.pause(INTERVAL)
                plt.clf()
        
        i += 1
        arr[i], arr[high] = arr[high], arr[i]

        plt.bar(X, arr)
        plt.title('Quicksort - sortowanie szybkie')
        plt.pause(INTERVAL)
        plt.clf()
        
        return i, arr

    quick_sort(l, 0, len(l) - 1)


if __name__ == '__main__':
    
    task1 = mp.Process(target=heap_sort_global, args=(L,))
    task2 = mp.Process(target=quic_sort_global, args=(L,))

    task1.start()
    task2.start()

    plt.show()